export const QUESTIONAIRE_ANSWER = 'QUESTIONAIRE_ANSWER'
export const CLEAR_QUESTIONAIRE_ANSWER = 'CLEAR_QUESTIONAIRE_ANSWER'
export const GET_REGULAR_QUESTIONS = 'GET_REGULAR_QUESTIONS'
export const GET_QUESTIONS_LISTING = 'GET_QUESTIONS_LISTING'
