export const GET_DOSAGE_VARIENTS = 'GET_DOSAGE_VARIENTS';
export const GET_DOSAGE_VARIENTS_LISTING = 'GET_DOSAGE_VARIENTS_LISTING';
export const SET_SELECTED_DOSAGE_VARIENT = 'SET_SELECTED_DOSAGE_VARIENT';
