export const DECIDING_ANSWER = 'DECIDING_ANSWER'
export const CLEAR_DECIDING_ANSWERS = 'CLEAR_DECIDING_ANSWERS'
export const GET_DECIDING_QUESTIONS = 'GET_DECIDING_QUESTIONS'
export const SELECTED_DECIDING_ANSWERS = 'SELECTED_DECIDING_ANSWERS'
export const SAVE_DECIDING_ANSWERS = 'SAVE_DECIDING_ANSWERS'
export const SET_START_SESSION = 'SET_START_SESSION';
export const GET_SESSION_ID = 'GET_SESSION_ID';