export const SET_NAME = 'SET_NAME'
export const SET_LAST_NAME = 'SET_LAST_NAME'
export const SET_DOB = 'SET_DOB'
export const SET_ERROR = 'SET_ERROR'
export const SET_GENDER = 'SET_GENDER'
export const GET_ADDRESS = 'GET_ADDRESS'
export const GET_ADDRESS_LISTING = 'GET_ADDRESS_LISTING'
export const SET_ADDRESS = 'SET_ADDRESS'