export const GET_CLIENT_SECRET_KEY = 'GET_CLIENT_SECRET_KEY'
export const SAVE_COMPLETE_QUESTION = 'SAVE_COMPLETE_QUESTION'
export const CREATE_ORDER = 'CREATE_ORDER'
export const SAVE_CREATE_ORDER_RESPONSE = 'SAVE_CREATE_ORDER_RESPONSE'
